spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 



#JPA seeting  
  jpa.hibernate.ddl_auto: create
  jpa.properties.hibernate.format_sql: true     
